[package]
name = "wasm-processor-socket"
version = "0.1.0"
authors = ["Yuto Kawamura <kawamuray.dadada@gmail.com>"]
edition = "2018"

[lib]
crate-type = ['cdylib']

[dependencies]
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
